name: .NET Core Desktop

on:
  push:
    branches: ['*']'
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release] # Optionally include Debug configuration "[Debug, Release]"

    runs-on: windows-latest

    env:
      Solution_Name: src/QuickShortcutList.sln
      Output_Directory: src/bin/Release/net8.0-windows/publish

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    # Publish application
    - name: Publish application
      run: dotnet publish $env:Solution_Name
      env:
        Configuration: ${{ matrix.configuration }}