name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*' # Triggers on version tags
  pull_request:
    branches: [ "main" ]
  release:
    types: [created]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release] # Optionally include Debug configuration "[Debug, Release]"

    runs-on: windows-latest

    env:
      Solution_Name: src/QuickShortcutList.sln
      Output_Directory: src/bin/Release/net8.0-windows/publish

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    # Publish application
    - name: Publish application
      run: dotnet publish $env:Solution_Name
      env:
        Configuration: ${{ matrix.configuration }}

    - name: Create ZIP archive
      if: matrix.configuration == 'Release' && startsWith(github.ref, 'refs/tags/')
      run: |
        $version = "${{ github.ref_name }}"
        $zipFileName = "QuickShortcutList-$version.zip"
        Compress-Archive -Path "${{ env.Output_Directory }}/*" -DestinationPath $zipFileName
      shell: pwsh

    - name: Create GitHub Release
      if: matrix.configuration == 'Release' && startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: QuickShortcutList-${{ github.ref_name }}.zip
        name: QuickShortcutList ${{ github.ref_name }}
        body: |
          QuickShortcutList release version ${{ github.ref_name }}
          
          ## What's New
          - See commit history for details
        draft: false
        prerelease: ${{ contains(github.ref, '-rc') || contains(github.ref, '-beta') || contains(github.ref, '-alpha') }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}