name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*' # Triggers on version tags
  pull_request:
    branches: [ "main" ]
  release:
    types: [created]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    env:
      Solution_Name: src/QuickShortcutList.sln
      Output_Directory: src/bin/Release/net8.0-windows/publish

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    # Publish application
    - name: Publish application
      run: dotnet publish $env:Solution_Name
      env:
        Configuration: ${{ matrix.configuration }}

    # Create zip file with version name instead of commit SHA
    - name: Create ZIP archive
      if: matrix.configuration == 'Release' && startsWith(github.ref, 'refs/tags/')
      run: |
        $version = "${{ github.ref_name }}"
        $zipFileName = "QuickShortcutList-$version.zip"
        Compress-Archive -Path "${{ env.Output_Directory }}/*" -DestinationPath $zipFileName
      shell: pwsh

    # Upload the ZIP file as artifact (only for Release configuration)
    - name: Upload build artifact
      if: matrix.configuration == 'Release'
      uses: actions/upload-artifact@v4
      with:
        name: QuickShortcutList-Release
        path: QuickShortcutList-${{ github.ref_name }}.zip
        retention-days: 90